# Generated by Django 3.2.5 on 2021-08-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed group', max_length=30)),
                ('discipline', models.CharField(default='unnamed group', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='John', max_length=30)),
                ('lastname', models.CharField(default='Doe', max_length=30)),
                ('age', models.IntegerField(default=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='John', max_length=30)),
                ('lastname', models.CharField(default='Doe', max_length=30)),
                ('age', models.IntegerField(default=16)),
                ('dicsiplines', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
