language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - cp example.env .env
  - pip check
  - python manage.py check
  - python manage.py makemigrations --check --dry-run
  - flake8