# Generated by Django 3.2.5 on 2021-09-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='John', max_length=30)),
                ('lastname', models.CharField(default='Doe', max_length=30)),
                ('age', models.IntegerField(default=16)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('disciplines', models.CharField(default='None', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
