# Generated by Django 3.2.5 on 2021-08-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='dicsiplines',
            new_name='disciplines',
        ),
    ]
