# Generated by Django 3.2.5 on 2021-08-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_disciplines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='disciplines',
            field=models.CharField(default='', max_length=50),
        ),
    ]
