# Generated by Django 3.2.5 on 2021-08-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_alter_teacher_disciplines'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
