# Generated by Django 3.2.5 on 2021-09-09 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '__first__'),
        ('students', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed group', max_length=30)),
                ('discipline', models.CharField(default='unnamed discipline', max_length=30)),
                ('headman', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('students', models.ManyToManyField(related_name='students2group', to='students.Student')),
                ('teacher', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
