# Generated by Django 3.2.5 on 2021-08-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed group', max_length=30)),
                ('discipline', models.CharField(default='unnamed discipline', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
